### ISSUE TITLE
Allow to work without @Deployment annotation

### ISSUE THREAD

**Issue by berndruecker** [camunda-community-hub/camunda-bpm-process-test-coverage#29]
When working without the @Deployment annotation in test cases (e.g. with Spring Boot) the test coverage should still work.

We discussed that it is a good heuristic to use the latest Deployment as a default in this case. I could imagine something like this: https://github.com/camunda/camunda-bpm-process-test-coverage/commit/6b9430bd34648552fb74ea6b76592772da4482ef (but a bit more robust).

**Comment by berndruecker** [comment]
Probably related to https://github.com/camunda/camunda-bpm-process-test-coverage/issues/16

**Comment by berndruecker** [comment]
The problem I have with such an easy fix is that I don't get results because of:

`13:48:04.359 [main] WARN  o.c.b.e.p.l.PathCoverageExecutionListener - Coverage execution listener in use but no coverage run state assigned!`

**Comment by paulbors** [comment]
Works for me with activity.cfg.xml in test resources set to:
`
<?xml version="1.0" encoding="UTF-8"?>

<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd">

    <bean id="processEngineConfiguration"
          class="org.camunda.bpm.extension.process_test_coverage.junit.rules.ProcessCoverageInMemProcessEngineConfiguration">
        <property name="jdbcUrl" value="jdbc:h2:mem:activiti" />
        <property name="databaseSchemaUpdate" value="true" />
        <property name="jobExecutorActivate" value="false" />
        <property name="mailServerPort" value="5025" />
        <property name="enableExpressionsInAdhocQueries" value="true" />
    </bean>

</beans>
`

**Comment by akamble-incomm** [comment]
No update on this? My reason for wanting to avoid using @Deployment is that I need to deploy my processes with a tenant ID, which (from what I can tell) can't be done with @Deployment. That's why I'm using Camunda's repositoryService to deploy my shared/multi-tenant process definitions. But then of course, test coverage does not happen.

**Comment by berndruecker** [comment]
Would you be willing to propose a PR?

**Comment by rohwerj** [comment]
Since version 1.0.2 it is possible to use the spring test integration, which doesn't require using the Deployment annotation.
All process definitions, which are deployed in the spring boot application under test, can be used in the test and will be shown in the process coverage report.
This issue can therefore be closed or what do you think @zambrovski

**Comment by zambrovski** [comment]
Agree! Thank you for taking care.
