### ISSUE TITLE
Separate coverage collection from report generation

### ISSUE THREAD

**Issue by zambrovski** [camunda-community-hub/camunda-bpm-process-test-coverage#75]
As a user of the rule I want to manage if I want to create reports out of coverage data or not.

**Comment by stephanpelikan** [comment]
Hi Simon,

Thanky you for reactivating this project!

I use the Process Coverage in different context than JUnit-tests. I use the CoverageTestRunState to access the process coverage but had to copy the methods initializeListenerRunState (https://github.com/camunda/camunda-bpm-process-test-coverage/blob/c2b69e06373857a73ff78511371b208d410e0741/core/src/main/java/org/camunda/bpm/extension/process_test_coverage/junit/rules/TestCoverageProcessEngineRule.java#L261) and initializeTestMethodCoverage https://github.com/camunda/camunda-bpm-process-test-coverage/blob/c2b69e06373857a73ff78511371b208d410e0741/core/src/main/java/org/camunda/bpm/extension/process_test_coverage/junit/rules/DefaultCoverageTestRunState.java#L93.

I plan to refactor this to avoid duplicating code. Is this issue meant to separate also on the level beyond the TestCoverageProcessEngineRule or just switch the on/off the generation of reports? I latter than I would create a new issue for my refactoring. If first then I would like to support you since I have a use case to prove this separation. 

Stephan

**Comment by zambrovski** [comment]
Hi Stephan,

Please create an issue if you want to provide some enhancement or feature. Independent from the current issue, I'm interested in it.

Have a look on #76. I just synchronized with @dominikhorn93 from FlowCov and the plan is to refactor the coverage data collection in a way that not only JUnit Rule can generate reports out of this. We spoke about ability to use the same coverage collector in different other scenarios (like injecting it as an engine plugin and use it for monitoring or performance tests and collect not only coverage but also timings, variables, whatever...)

Cheers,

Simon

**Comment by stephanpelikan** [comment]
I saw #76 but I use it in Spring boot environment with a process engine running workflows. I need a Java API. So only the core module as described in #77 applied to an existing Camunda environment.

**Comment by zambrovski** [comment]
The idea of #77 is to have a Java API for collecting flow nodes at first place and another Java API to construct the reports. The wiring between these two (independent) functionalities will be moved to separate modules for JUnit4, JUnit5 (and probabaly something for the SpringBoot runner) which should allow for using the coverage collection as a usual plugin independent from the test frameworks. I see a great potential in providing this kind of information of the process progress (independent from test coverage).
