### ISSUE TITLE
TestCoverageProcessEngineRule failed with new Scenario library release(V1.1.1)

### ISSUE THREAD

**Issue by stef201** [camunda-community-hub/camunda-bpm-process-test-coverage#91]
`camunda-bpm-assert-scenario` V1.1.1 released a few days ago, now has a possibility to mock Call Activities (`scenario.waitsAtMockedCallActivity`). More details [here](https://forum.camunda.org/t/mocking-call-activities-for-the-camunda-scenario-tests/27161)

When the test is run by `ProcessEngineRule` - there is no problem(test passes)
But when the test is run by `TestCoverageProcessEngineRule` I get a `NullPointeException`(see attached stack trace)
[test_coverage_error.txt](https://github.com/camunda-community-hub/camunda-bpm-process-test-coverage/files/6436592/test_coverage_error.txt)

I hope it helps, and that this problem is of interest.

**Comment by richardbizik** [comment]
I had the same problem and it turns out I was missing Deployment annotation on my test and I did not pass this check
https://github.com/camunda-community-hub/camunda-bpm-process-test-coverage/blob/cf29cf03b8669dc6207ca37913c3ea71f4f657d4/extension/junit4/src/main/java/org/camunda/bpm/extension/process_test_coverage/junit/rules/TestCoverageProcessEngineRule.java#L134
Which resulted in method run not being properly initialized. Hope this helps.

**Comment by zambrovski** [comment]
Could you please make a new try? 
If not - I'll close the ticket

**Comment by zambrovski** [comment]
Since there is no respond from the issuer, I'm closing the issue.
