### ISSUE TITLE
Publishing snapshot to Nexus failed

### ISSUE THREAD

**Issue by zambrovski** [camunda-community-hub/camunda-bpm-process-test-coverage#94]
For some reason, the CI pipeline publishing a new snapshot to Nexus failed with an error, saying that the repository is read-only...

See https://github.com/camunda-community-hub/camunda-bpm-process-test-coverage/runs/3911091167?check_suite_focus=true

**Comment by zambrovski** [comment]
Thank you, I assumed it is about the Camunda Artifacts only, not about Community HUB projects, but now it is clear.

Is there anywhere a plan or a documentation for the HUB projects, describing the steps for the migration?

Cheers,

Simon

**Comment by Langleu** [comment]
Hey Simon, both Camunda Artifacts and Community HUB Artifacts share the same Artifact storage (Nexus / Artifactory), therefore, they will be migrated all in the same step.
There is no further documentation apart from the links mentioned above that are public, which do apply to both projects.
As described in the links and mentioned prior, we plan to continue supporting the `https://app.camunda.com/nexus` domain due to which no further steps are required.

If there is anything else you'd like further insights into or something that is missing in particular, let me know!

Best
Lars

**Comment by zambrovski** [comment]
Hi Lars,

Will wait until you are finished. Will be any change in the credentials required by the build pipeline or will it be transparent for us?

Cheers and thanks 

Simon

**Comment by Langleu** [comment]
Hey @zambrovski, good news! Migration of the files was quicker than anticipated.
I reran the [pipeline](https://github.com/camunda-community-hub/camunda-bpm-process-test-coverage/runs/3917931192?check_suite_focus=true) for you, which uploaded the artifact via our Nexus URL to [Artifactory](https://camunda.jfrog.io/ui/repos/tree/General/camunda-bpm-community-extensions-snapshots%2Forg%2Fcamunda%2Fbpm%2Fextension%2Fcamunda-bpm-process-test-coverage-junit4%2F1.0.0-SNAPSHOT%2Fcamunda-bpm-process-test-coverage-junit4-1.0.0-20211017.084000-5.jar).

**Comment by ingorichtsmeier** [comment]
Ah, sorry! The issue is raised in my fork, not in the community hub repo.
